Feature project
Team-7-WestLoveRock/taskApi pull request #8
Opened 2023-06-06 18:59 UTC by mmm4707

내일 수정할것 : service로직에서 entity가아닌 dto로 적용하는것, createAt 포매팅 관련,  컨트롤러 타입부분

2023-06-06 19:03 UTC, mmm4707 commented
뷰페이지까지 완성은 해놨습니다 자잘자잘하게 수정할것들이 있긴합니다

2023-06-06 23:51 UTC, mmm4707 commented
에러처리 핸들러 생성

2023-06-07 00:55 UTC, 10kseok requested changes
각 파일별로 리뷰가 있으니 확인해주세요

2023-06-07 00:55 UTC, 10kseok commented on src/main/java/com/nhnacademy/westloverock/taskapi/controller/ProjectController.java
Controller에서는 Project 엔터티를 반환하는 것보다 ProjectDTO를 반환해주는 게 나아보입니다.

2023-06-07 00:55 UTC, 10kseok commented on src/main/java/com/nhnacademy/westloverock/taskapi/controller/ProjectController.java
데이터를 가져올 때 get 말고 find를 사용해주세요!
get은 필드 가져올 때 사용해주세요.

2023-06-07 00:55 UTC, 10kseok commented on src/main/java/com/nhnacademy/westloverock/taskapi/dto/ProjectDto.java
ProjectDTO에 ProjectId가 빠져있습니다

2023-06-07 00:55 UTC, 10kseok commented on src/main/java/com/nhnacademy/westloverock/taskapi/handler/GlobalExceptionHandler.java
여러 Exception을 처리해야할 상황이 많으므로 아래 파일을 참고하여 응답코드별로 예외를 처리할 수 있게 변경해주세요.

[CommonRestControllerAdvice.java.zip](https://github.com/Team-7-WestLoveRock/taskApi/files/11671375/CommonRestControllerAdvice.java.zip)

2023-06-07 00:55 UTC, 10kseok commented on src/main/resources/application.properties
ddl-auto 옵션에 update를 주면 칼럼 삭제를 지원하지 않고 추가나 수정만을 지원해 추후 문제가 발생할 가능성이 있다고 합니다.
안정성을 위하여 create-drop 옵션으로 바꿔서 진행바랍니다.

2023-06-07 06:45 UTC, 10kseok approved these changes
확인했습니다.

2023-06-07 06:45 UTC, merged